spring:
  profiles:
    active: dev
  application:
    name: provider-movie

server:
  port: 9003

mybatis:
  mapperLocations: classpath:mybatis/mapper/*.xml
mapper:
    mappers:
        - com.github.weiwei02.microservice.data.dao.SuperMapper
    not-empty: false
    identity: MYSQL

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

eureka:
  instance:
    appname: ${spring.application.name}
    virtualHostName: ${spring.application.name}
    secureVirtualHostName: ${spring.application.name}
    nonSecurePort: ${server.port}

    #注册服务默认心跳时间为30秒（Indicates how often (in seconds) the eureka client needs to send heartbeats to eureka server to indicate that
    #it is still alive. If the heartbeats are not received for the period specified in leaseExpirationDurationInSeconds,
    #eureka server will remove the instance from its view, there by disallowing traffic to this instance）
    leaseRenewalIntervalInSeconds: 2

    #服务最后一次心跳到服务被移除的时间，默认90秒
    lease-expiration-duration-in-seconds: 4

    #实例使用ip代替hostName
    preferIpAddress: true

    status-page-url-path: /health

    #服务初始化状态 枚举值如：UP、DOWN、STARTING、OUT_OF_SERVICE、UNKNOWN，不设置默认为UP
    initial-status: UP

  client:
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled: true
    registryFetchIntervalSeconds: 2
    instance-info-replication-interval-seconds: 4
    initial-instance-info-replication-interval-seconds: 4

    #Indicates how often(in seconds) to poll for changes to eureka server information. Eureka servers could be added or removed and this setting controls how soon the eureka clients should know about it.
    eureka-service-url-poll-interval-seconds: 2

    #Indicates whether server can redirect a client request to a backup server/cluster.
    #If set to false, the server will handle the request directly, If set to true, it may send HTTP redirect to the client, with a new server location.
    allow-redirects: true
#
    serviceUrl:
      #defaultZone: http://192.168.21.20:18000/eureka/,http://192.168.21.29:18000/eureka/
      defaultZone: http://localhost:8888/eureka/
#      defaultZone: http://localhost:1111/eureka/

  server:
    enableSelfPreservation: false

    #服务端调用evict频率,如果此值设置过大，会导致服务停止后不能及时被发现，默认60s
    eviction-interval-timer-in-ms: 2000

  #默认default
  datacenter: default

  #默认test
  environment: test