spring:
  profiles:
    active: dev

server:
  port: 8888
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8888/eureka/
